# Specify image
FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim

# Define working directory
WORKDIR /app

# Copy published file to your application
COPY ./publish .

# Define entry point 
ENTRYPOINT ["dotnet", "BotRAG.dll"]